### ISSUE TITLE
How to schedule learning?

### ISSUE THREAD

**Issue by Positron010** [fasiha/meguro#1]
Hi Ahmed, and thanks for building meguro!

Just a question, is there any way you can know through when to come and do your flashcards again? i.e. how does meguro schedule learning? Should I run it on the same file again and see if it asks me or not? 

Thanks!

**Comment by fasiha** [comment]
Hello! Sorry for the delay. Meguro has no "scheduling", that is, it doesn't have a concept of when you should review flashcards. You review until you're tired of reviewing: if you're seeing quizzes that you're familiar with, close the app and do something else 😄. This is my preferred approach (in contrast to Anki e.g. that schedules due dates for flashcards).

In a bit more detail, Meguro will just reload the file, figure out the flashcard with lowest predicted recall probability, and ask you that, over and over again. If you know only one flashcard, it will keep asking you that, over and over again.

**Comment by Positron010** [comment]
Thanks for the reply @fasiha !
