### ISSUE TITLE
Allowing more than one word questions & the choice to reveal the answer without typing

### ISSUE THREAD

**Issue by Positron010** [fasiha/meguro#2]
Hi Ahmed,

I would like to use meguro, but there are some drawbacks that are preventing me, and since I'm not a developer, I couldn't resolve them by myself.

1. The question should only consist of one word. This is useful in learning vocab, but I think it will be much better if the user was allowed to have more than one word question, separated from the answer by a special character or something.
2. Again this is useful for learning vocab, but for a broader audience, I think it might be useful to give the choice to reveal the anser without typing.

I would be grateful if you add these suggestions.
Thanks.

**Comment by fasiha** [comment]
> if the user was allowed to have more than one word question, separated from the answer by a special character or something

Yes, we can do this. Maybe something like, you can specify a custom separator when you invoke Meguro, something like `npx meguro quiz.md --separator '::'`?

> give the choice to reveal the anser without typing

Hmm, can you explain the idea behind this? If I don't know the answer, I type in something nonsensical: Meguro will treat that as a failure and update the Ebisu model accordingly. Or, the other possibility is that your card is a "front-only" card like "👒 @@" in the README, in that situation, Meguro says "Enter→you remember the card. Any other text→you forgot it".

Can you help me understand what you'd like to see here?

**Comment by fasiha** [comment]
What do you think of custom separators: https://github.com/fasiha/meguro#custom-separator ?

**Comment by Positron010** [comment]
Hi @fasiha ! Thanks for replying and taking my humble feedback in consideration!

The main idea behind this can be seen in Anki & other SR applications like SuperMemo, where the user rates himself. This is important in many cases especially in the context of the sciences like medicine, ..etc, where the user doesn't need to know the spelling of the word, because the questions are MCQs or the test is oral. Another case is if the answer doesn't need to be remembered verbatim, and the user can formulate the answer in his own words. Also, it will be a pain to write a long answer, if the answer of a question is long, & making sure all the spelling is correct at the same time!

Hope the idea is clear.

 I will try using the separators, and provide feedback.

Edit: The separators work! Just note that the example you provided as seen below, has no expected answer when run, because the program considers even the Japanese writing as a part of the question, and the part within the paranthesis is revealed after entering the answer.
 
 ☀️ 💖💗 sun 💖💗 soleil 💖💗 たいよう ("Oh Mr Sun, Sun, Mr Golden Sun") @@
 
 - Extra: I am not a developer so I might be wrong, but why don't you assign the separator between the question and the answer, rather than between words of the question, I think that will be more intuitive.
 
Thanks, Ahmed @fasiha !

**Comment by fasiha** [comment]
> the user rates himself. This is important in many cases especially in the context of the sciences like medicine, ..etc, where the user doesn't need to know the spelling of the word

Oh yes for sure. You can do this with Meguro like this: put the following in quiz.txt:
```
2 * 2 = 4 @@
5 * 2 = 10 @@
```
then invoke Meguro like this: `npx meguro -s __ quiz.txt`. We're telling Meguro the separator is a nonsense string that doesn't appear in our file (`__` can be replaced by anything that doesn't appear in your file), so it just shows you the front of the card with no back, and asks you to press Enter if you remembered it, or anything else if you didn't.

Example output:
```
➜ npx meguro -s ___ test.txt 
npx: installed 27 in 2.368s
Enter→you remember the card. Any other text→you forgot it.
2 * 2 = 4 :: [I JUST HIT ENTER HERE]
💇‍♀️⚡️🎊🍌. 
Type a number to scale this card's easiness, Enter to see next question, or anything else to quit > 
Enter→you remember the card. Any other text→you forgot it.
5 * 2 = 10 :: [AGAIN I JUST HIT ENTER]
💇‍♀️⚡️🎊🍌. 
Type a number to scale this card's easiness, Enter to see next question, or anything else to quit > 
Enter→you remember the card. Any other text→you forgot it.
2 * 2 = 4 :: oops i forgot this?!!?[ENTER]
🙅‍♂️👎❌🚷. 
Type a number to scale this card's easiness, Enter to see next question, or anything else to quit > 
Enter→you remember the card. Any other text→you forgot it.
5 * 2 = 10 :: ^C [I HIT CONTROL-C TO QUIT]
```

**Comment by Positron010** [comment]
Thanks for the reply @fasiha !

Yes, this works, but there is no answer to compare to so you know whether you answered right or not?

I think a workaround could be putting the answer in the parenthesis and leaving its original field empty, but that is not straight forward as providing the choice to reveal the answer by pressing space for example, and then prompting the user to either not rate himself and leave it to the program or enter a number like 1-again 2-hard 3-good 4-easy for example.

**Comment by fasiha** [comment]
> Yes, this works, but there is no answer to compare to so you know whether you answered right or not?

Ahh I see!!! Thanks for bearing with me, my apologies, I now see what you mean, my earlier explanation (for "front-only cards") won't help here, hmm, yes, that would be useful.

Hmm, from a workflow perspective though, this will be a big change: Meguro currently (1) shows you the front, (2) gets input from you, and (3) immediately scores the response and updates the Ebisu model.

The Anki workflow would mean Meguro (1) shows you the front, (2) gets input from you (to flip the card), (3) gets input from you a second time (for your score), and (4) finally updates the Ebisu model.

Let me think about how maybe we can combine the two workflows so they can both live in this one program and we can call it Meguro. If they can't be reasonably and ergonomically combined, then I could maybe create another program that uses the same *file* format, but uses the Anki-style quiz format.

**Comment by Positron010** [comment]
Thanks for your hard work @fasiha! Looking forward to the results! Thanks for taking my suggestions into consideration!

**Comment by Positron010** [comment]
You could also look at [leaf](https://github.com/ap4y/leaf) where the author managed to allow the user to choose between an auto rater, and a self rater, where in the auto you need to type the answer, and in the self you reveal it and rate your answer, and also provides ebisu algorithm as a choice @fasiha .

**Comment by fasiha** [comment]
Ok! It wasn't hard at all! Check it out now: if you have the following in test.txt:
```
Tinnitis // Disease of the ear I think @@
Hang nail // Troublesome condition of the finger or toe nails @@
```
and invoke it as
```
➜ npx meguro@latest test.txt -s //
npx: installed 33 in 2.434s
Tinnitis :: 
Expected answers: Disease of the ear I think.
Enter→you remembered, any other text→you forgot. 
💇‍♀️⚡️🎊🍌. 
Type a number to scale this card's easiness, Enter to see next question, or anything else to quit > 

Hang nail :: 
Expected answers: Troublesome condition of the finger or toe nails.
Enter→you remembered, any other text→you forgot. I TOTALLY FORGOT!!!???
🙅‍♂️👎❌🚷, expected: Troublesome condition of the finger or toe nails. 
```

Note I had to run `npx meguro@latest`, notice the `@latest`, to make npx fetch the just-published version, you might or might not need that?

As you can see above, and as I describe in https://github.com/fasiha/meguro/#detailed-usage, if you just hit Enter when you're prompted for an answer, you'll get into Anki-style self-grading mode where it will show you the answer(s) it was expecting (the back of the flashcard) and then invite you to grade yourself.

The old quiz style is also fully supported of course.

It looks a bit cooler too 😅:

<img width="780" alt="Screen Shot 2021-02-15 at 01 02 10" src="https://user-images.githubusercontent.com/37649/107910936-76a81000-6f29-11eb-91c0-bb4be8948486.png">

Let me know if you like this.

**Comment by Positron010** [comment]
Hi Ahmed! 
I just tried it, and it works! Thanks for the hard work! At least for me it is much better, with a wider functionality! 
Thanks again for being open to my humble suggestions! 
@fasiha
